name = "GeoGrids"
uuid = "22c7c615-cf67-4787-b800-cc81b4f1a63f"
authors = ["mconti"]
version = "0.5.0"

[deps]
AngleBetweenVectors = "ec570357-d46e-52ed-9726-18773498274d"
Clipper = "c8f6d549-b3ab-5508-a0d1-48fe138e8cc1"
CoordRefSystems = "b46f11dc-f210-4604-bfba-323c1ec968cb"
CountriesBorders = "ee40d4b5-31c3-4fe2-b6cc-5ac7adf7f414"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
PlotlyExtensionsHelper = "a7e57fc7-3548-4021-90c3-ac0e175068b1"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[extensions]
PlotlyBaseExt = "PlotlyBase"

[compat]
AngleBetweenVectors = "0.3.0"
CoordRefSystems = "0.10"
CountriesBorders = "0.4"
Dictionaries = "0.4.2"
LinearAlgebra = "1"
Meshes = "0.48"
PlotlyBase = "0.8.19"
PlotlyExtensionsHelper = "0.2.0"
StaticArrays = "1.9.7"
Unitful = "1.21.0"
julia = "1.10"
Clipper = "0.6.3"